const Graphs9 = {
  graphs: ["9 bcdefghi,aihdc,abd,acbhgfe,adf,aedg,afdh,agdbi,ahb",
          "9 bcdefghi,aihc,abhgfed,ace,adcf,aecg,afch,agcbi,ahb",
          "9 bcdefghi,aifedc,abd,acbe,adbf,aebihg,afh,agfi,ahfb",
          "9 bcdefghi,aic,abid,acigfe,adf,aedg,afdih,agi,ahgdcb",
          "9 bcdefgh,ahedc,abd,acbe,adbhgif,aeig,afieh,ageb,egf",
          "9 bcdefghi,aiedc,abd,acbe,adbihf,aehg,afh,agfei,aheb",
          "9 bcdefghi,aiedc,abd,acbe,adbif,aeihg,afh,agfi,ahfeb",
          "9 bcdefghi,aidc,abd,acbihe,adhgf,aeg,afeh,agedi,ahdb",
          "9 bcdefghi,aihgdc,abd,acbgfe,adf,aedg,afdbh,agbi,ahb",
          "9 bcdefghi,aihgc,abged,ace,adcgf,aeg,afecbh,agbi,ahb",
          "9 bcdefg,aghifc,abfed,ace,adcf,aecbihg,afhb,bgfi,bhf",
          "9 bcdefg,aghfc,abfed,ace,adcf,aecbhig,afihb,bgif,fhg",
          "9 bcdefg,aghifc,abfed,ace,adcf,aecbig,afihb,bgi,bhgf",
          "9 bcdefg,aghfic,abifed,ace,adcf,aecibhg,afhb,bgf,bfc",
          "9 bcdefg,aghfc,abfied,ace,adcif,aeicbhg,afhb,bgf,cfe",
          "9 bcdefgh,ahigc,abged,ace,adcgf,aeg,afecbih,agib,bhg",
          "9 bcdefghi,aihfdc,abd,acbfe,adf,aedbhg,afh,agfbi,ahb",
          "9 bcdefghi,aigdc,abd,acbge,adgf,aeg,afedbih,agi,ahgb",
          "9 bcdefg,agfc,abfhed,ace,adchif,aeihcbg,afb,cfie,ehf",
          "9 bcdefg,agfc,abfhied,ace,adcif,aeihcbg,afb,cfi,chfe",
          "9 bcdefg,agfhc,abhfied,ace,adcif,aeichbg,afb,bfc,cfe",
          "9 bcdefgh,ahfc,abfied,ace,adcif,aeicbhg,afh,agfb,cfe",
          "9 bcdefgh,ahc,abhd,achife,adf,aedihg,afh,agfidcb,dhf",
          "9 bcdefghi,aifc,abfd,acfe,adf,aedcbihg,afh,agfi,ahfb",
          "9 bcdefgh,ahic,abid,acie,adif,aeig,afih,agib,bhgfedc",
          "9 bcdefgh,ahidc,abd,acbie,adif,aeig,afih,agib,bhgfed",
          "9 bcdefgh,ahiedc,abd,acbe,adbif,aeig,afih,agib,bhgfe",
          "9 bcdefg,aghc,abhgid,acie,adif,aeig,afichb,bgc,cgfed",
          "9 bcdefgh,ahc,abhied,ace,adcif,aeig,afih,agicb,chgfe",
          "9 bcdefgh,ahgic,abied,ace,adcif,aeig,afibh,agb,bgfec",
          "9 bcdefg,aghc,abhd,achie,adihgf,aeg,afehb,bgeidc,dhe",
          "9 bcdefg,aghc,abhd,ache,adhigf,aeg,afeihb,bgiedc,ehg",
          "9 bcdefg,aghic,abihd,ache,adhgf,aeg,afehb,bgedci,bhc",
          "9 bcdefg,aghc,abhd,achie,adif,aeig,afihb,bgidc,dhgfe",
          "9 bcde,aefghic,abid,acie,adifb,beihg,bfh,bgfi,bhfedc",
          "9 bcde,aefghic,abid,acie,adifb,beig,bfih,bgi,bhgfedc",
          "9 bcde,aefghic,abihd,ache,adhfb,behg,bfh,bgfedci,bhc",
          "9 bcdef,afeghic,abid,acie,adigbf,aeb,beih,bgi,bhgedc",
          "9 bcde,aefghic,abid,acie,adigfb,beg,bfeih,bgi,bhgedc",
          "9 bcde,aefghc,abhd,ache,adhifb,beig,bfih,bgiedc,ehgf",
          "9 bcde,aefgc,abgd,acghe,adhifb,beig,bfihdc,dgie,ehgf",
          "9 bcde,aefgc,abghd,achige,adgfb,beg,bfedihc,cgid,dhg",
          "9 bcde,aefgc,abghid,acihge,adgfb,beg,bfedhc,cgdi,chd",
          "9 bcde,aefghc,abhgid,acige,adgfb,beg,bfedich,bgc,cgd",
          "9 bcdef,afghc,abhid,acihfe,adf,aedhgb,bfh,bgfdic,chd",
          "9 bcdefg,aghic,abihd,achge,adgf,aeg,afedhb,bgdci,bhc",
          "9 bcdef,afeghc,abhid,acihe,adhgbf,aeb,beh,bgedic,chd",
          "9 bcde,aefgc,abghd,achfe,adfb,bedhig,bfihc,cgifd,fhg",
          "9 bcde,aefghc,abhgid,acife,adfb,bedig,bfich,bgc,cgfd",
          "9 bcde,aefgc,abghd,achie,adifb,beig,bfihc,cgid,dhgfe"]
};

module.exports = Graphs9;
